const Privacy = () => {
  return (
    <div
      className="absolute top-16 bg-white text-black z-50 max-h-[80vh] overflow-y-scroll 
                p-10 mx-10 md:mx-24 lg:mx-56 rounded-lg border"
      id="privacy"
    >
      <div className="flex lg:space-x-[75%] mb-[10px] popupnav space-x-[55%] lg:px-5 lg:py7">
        <h1 className="lg:text-3xl font-extrabold  text-xl">Privacy Policy</h1>
        <h1
          id="closeprivacypopup"
          onClick={() => {
            document.getElementById("privacy").style.display = "none";
            window.location.reload();
          }}
          className="absolute right-3 top-3 cursor-pointer text-3xl font-bold lg:font-extrabold"
        >
          X
        </h1>
      </div>
      <div className="line mb-[10px]"></div>
      <div className="terms-content lg:mt-7">
        <h1>INTRODUCTION</h1>
        <p>
          Thank you for choosing to be part of our community at THINKWHT,
          operated by ELVDRIVE SCOOTER LLP ("we", "us", "our", "Thinkwht"). We
          are committed to protect your personal information and your right to
          privacy. We use your data to provide and improve Service. By using
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this Privacy
          Policy, the terms used in this Privacy Policy have the same meanings
          as in our Terms and Conditions.
        </p>
        <p>
          If you have any questions about our practices with regards to your
          personal information, please contact to thinkwht@gmail.com
        </p>
        <p>
          This privacy notice describes how we might use your information if
          you:
        </p>

        <p>❏ Visit our website https://thinkwht.com/</p>
        <p>
          ❏ Engage with us in any other ways - including any sales, marketing,
          events or workshops.
        </p>

        <p>This privacy policy applies to https://thinkwht.com/ .</p>

        <p>
          By accessing or using our service, you signify that you have read,
          understood and agreed to collection, storage, use and disclosure of
          your personal information as described in this Privacy Policy and all
          other regulations as described in the Terms and Conditions.
        </p>

        <h2>DEFINITION AND KEY TERMS </h2>

        <p>
          ● Cookie: small amount of data generated by a website and saved by
          your web browser. It is used to identify your browser, provide
          analytics, and remember information about you such as your language
          preference or login information.
        </p>
        <p>
          ● Company: when this policy mentions "Company," "we," us," or "our,"
          it refers to ELVDRIVE SCOOTER LLP, doing business as THINKWHT;
          Ramprastha City, The edge Sector 37D Gurgaon, Haryana 122004.
        </p>
        <p>
          ● Device: any internet connected device such as a phone, tablet,
          computer or any other device that can be used to visit THINKWHT and
          use the services.
        </p>
        <p>
          ● IP address: Every device connected to the Internet is assigned a
          number known as an Internet protocol (IP) address. These numbers are
          usually assigned in geographic blocks. An IP address can often be used
          to identify the location from which a device is connecting to the
          Internet.
        </p>
        <p>
          ● Personnel: refers to those individuals who are employed by THINKWHT
          or are under contract to perform a service on behalf of one of the
          parties.
        </p>
        <p>
          ● Service: refers to the service provided by THINKWHT as described in
          the relative terms (if available) and on this platform.
        </p>
        <p>
          ● Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide our content
          or whose products or services we think may interest you.
        </p>
        <p>
          ● Website: THINKWHT site, which can be accessed via this URL:
          https://thinkwht.com/and its subdomains.
        </p>
        <p>
          ● PERSONAL DATA: means data about a living individual who can be
          identified from those data (or from those and other information either
          in our possession or likely to come into our possession). Any
          information that directly, indirectly, or in connection with other
          information – including a personal identification number - allows for
          the identification or identify ability of a natural person.
        </p>
        <p>
          ● USAGE DATA: is data collected automatically either generated by the
          use of Service or from Service infrastructure itself (for example, the
          duration of a page visit).
        </p>
        <p>
          ● DATA CONTROLLER means a natural or legal person who (either alone or
          jointly or in common with other persons) determines the purposes for
          which and the manner in which any personal data are, or are to be,
          processed. For the purpose of this Privacy Policy, we are a Data
          Controller of your data.
        </p>
        <p>
          ● DATA PROCESSORS (OR SERVICE PROVIDERS) mean any natural or legal
          person who processes the data on behalf of the Data Controller. We may
          use the services of various Service Providers in order to process your
          data more effectively.
        </p>
        <p>
          ● DATA SUBJECT is any living individual who is the subject of Personal
          Data.
        </p>
        <p>
          ● THE USER/Customer/"You": refers to any individual person or entity
          browsing, accessing, using our Service or making any purchase. The
          User corresponds to the Data Subject, who is the subject of Personal
          Data.
        </p>

        <h1>WHAT INFORMATION DO WE COLLECT? </h1>

        <h2>Personal information you disclose to us</h2>
        <p>In Short: We collect personal information that you provide to us.</p>
        <p>
          We collect personal information that you voluntarily provide to us
          when you register on the Services, express an interest in obtaining
          information about us or our products and Services, when you
          participate in activities on the Services (such as by posting messages
          in our online forums or entering competitions, contests or giveaways)
          or otherwise when you contact us.
        </p>

        <p>
          The personal information that we collect depends on the context of
          your interactions with us and the Services, the choices you make and
          the products and features you use. The personal information we collect
          may include the following:
        </p>

        <p>
          ➢ Personal Information Provided by You: We collect names; phone
          numbers; email; usernames; passwords; billing addresses; and other
          similar information.
        </p>
        <p>
          ➢ Payment Data: We may collect data necessary to process your payment
          if you make purchases, such as your payment instrument number (such as
          a credit card number), and the security code associated with your
          payment instrument. All payment data is stored by Payment Gateway.
        </p>

        <h3>Information automatically collected</h3>
        <p>
          In Short: Some information - such as your Internet Protocol (IP)
          address and/or browser and device characteristics – is collected
          automatically when you visit our Services.
        </p>
        <p>
          We automatically collect certain information when you visit, use or
          navigate the Services. This information does not reveal your specific
          identity (like your name or contact information) but may include
          device and usage information, such as your IP address, browser and
          device characteristics, operating system, language preferences,
          referring URLS, device name, country, location, information about how
          and when you use our Services and other technical information. This
          information is primarily needed to maintain the security and operation
          of our Services, and for our internal analytics and reporting
          purposes.
        </p>

        <p>
          Like many businesses, we also collect information through cookies and
          similar technologies. Cookies are files with a small amount of data
          which may include an anonymous unique identifier. Cookies are sent to
          your browser from a website and stored on your device. Other tracking
          technologies are also used such as beacons, tags and scripts to
          collect and track information and to improve and analyse our Service.
        </p>

        <p>
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>
        <p>❖ Session Cookies: We use Session Cookies to operate our Service.</p>
        <p>
          ❖ Preference Cookies: We use Preference Cookies to remember your
          preferences and various settings.
        </p>
        <p>
          ❖ Security Cookies: We use Security Cookies for security purposes.
        </p>
        <p>
          ❖ Advertising Cookies: Advertising Cookies are used to serve you with
          advertisements that may be relevant to you and your interests.
        </p>

        <p>The information we collect includes: </p>
        <p>
          ➢ Log and Usage Data: Log and usage data is service-related,
          diagnostic, usage and performance information our servers
          automatically collect when you access or use our Services and which we
          record in log files. Depending on how you interact with us, this log
          data may include your IP address, device information, browser type and
          settings and information about your activity in the Services (such as
          the date/time stamps associated with your usage, pages and files
          viewed, searches and other actions you take such as which features you
          use), device event information (such as system activity, error reports
          (sometimes called 'crash dumps') and hardware settings).
        </p>
        <p>
          ➢ Device Data: We collect device data such as information about your
          computer, phone, tablet or other device you use to access the
          Services. Depending on the device used, this device data may include
          information such as your IP address (or proxy server), device and
          application identification numbers, location, browser type, hardware
          model, Internet service provider and/or mobile carrier, operating
          system and system configuration information.
        </p>
        <p>
          ➢ Location Data: We collect location data such as information about
          your device's location, which can be either precise or imprecise. How
          much information we collect depends on the type and settings of the
          device you use to access the Services. For example, we may use GPS and
          other technologies to collect geolocation data that tells us your
          current location (based on your IP address). You can opt out of
          allowing us to collect this information either by refusing access to
          the information or by disabling your Location setting on your device.
          Note however, if you choose to opt out, you may not be able to use
          certain aspects of the Services.
        </p>

        <h1>HOW DO WE USE YOUR INFORMATION?</h1>

        <p>
          In Short: We process your information for purposes based on legitimate
          business interests, the fulfilment of our contract with you,
          compliance with our legal obligations, and/or your consent. We use
          personal information collected via our Services for a variety of
          business purposes described below. We process your personal
          information for these purposes in reliance on our legitimate business
          interests, in order to enter into or perform a contract with you, with
          your consent, and/or for compliance with our legal obligations. We
          indicate the specific processing grounds we rely on next to each
          purpose listed below.
        </p>

        <p>We use the information we collect or receive: - </p>
        <p>
          ● To post testimonials: We post testimonials on our Services that may
          contain personal information. Prior to posting a testimonial, we will
          obtain your consent to use your name and the content of the
          testimonial. If you wish to update, or delete your testimonial, please
          contact us at thinkwht@gmail.com and be sure to include your name,
          testimonial location, and contact information.
        </p>
        <p>
          ● Request feedback: We may use your information to request feedback
          and to contact you about your use of our Services.
        </p>
        <p>
          ● To enable user-to-user communications: We may use your information
          in order to enable user-to-user communications with each user's
          consent.
        </p>
        <p>
          ● To manage user accounts: We may use your information for the
          purposes of managing our account and keeping it in working order.
        </p>
        <p>
          ● To send administrative information to you: We may use your personal
          information to send you product, service and new feature information
          and/or information about changes to our terms, conditions, and
          policies.
        </p>
        <p>
          ● To protect our Services: We may use your information as part of our
          efforts to keep our Services safe and secure (for example, for fraud
          monitoring and prevention).
        </p>
        <p>
          ● To enforce our terms, conditions and policies for business purposes,
          to comply with legal and regulatory requirements or in connection with
          our contract.
        </p>
        <p>
          ● To respond to legal requests and prevent harm: If we receive a
          subpoena or other legal request, we may need to inspect the data we
          hold to determine how to respond.
        </p>
        <p>
          ● Fulfil and manage your orders: We may use your information to fulfil
          and manage your orders, payments, returns, and exchanges made through
          the Services.
        </p>
        <p>
          ● Administer prize draws and competitions: We may use your information
          to administer prize draws and competitions when you elect to
          participate in our competitions.
        </p>
        <p>
          ● To deliver and facilitate delivery of services to the user: We may
          use your information to provide you with the requested service.
        </p>
        <p>
          ● To respond to user inquiries/offer support to users: We may use your
          information to respond to your inquiries and solve any potential
          issues you might have with the use of our Services.
        </p>
        <p>
          ● To send you marketing and promotional communications: We and/or our
          third-party marketing partners may use the personal information you
          send to us for our marketing purposes, if this is in accordance with
          your marketing preferences. For example, when expressing an interest
          in obtaining information about us or our Services, subscribing to
          marketing or otherwise contacting us, we will collect personal
          information from you. You can opt-out of our marketing emails at any
          time.
        </p>
        <p>
          ● Deliver targeted advertising to you: We may use your information to
          develop and display personalized content and advertising (and work
          with third parties who do so) tailored to your interests and/or
          location and to measure its effectiveness.
        </p>
        <p>
          ● For other business purposes: We may use your information for other
          business purposes, such as data analysis, identifying usage trends,
          determining the effectiveness of our promotional campaigns and to
          evaluate and improve our Services, products, marketing and your
          experience. We may use and store this information in aggregated and
          anonymized form so that it is not associated with individual end users
          and does not include personal information.
        </p>

        <h1>RETENTION OF DATA </h1>

        <p>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies.
        </p>

        <p>
          We will also retain Usage Data for internal analysis purposes. Usage
          Data is generally retained for a shorter period, except when this data
          is used to strengthen the security or to improve the functionality of
          our Service, or we are legally obligated to retain this data for
          longer time periods.
        </p>

        <p>
          When we have no ongoing legitimate business need to process your
          personal information, we will either delete or anonymize such
          information, or, if this is not possible (for example, because your
          personal
        </p>
        <p>
          information has been stored in backup archives), then we will securely
          store your personal information and isolate it from any further
          processing until deletion is possible.
        </p>

        <h1>WILL YOUR INFORMATION BE SHARED WITH THIRD PARTIES? </h1>

        <p>We may share your data that we hold on the following basis:</p>

        <p>
          ➢ Consent: We may process your data if you have given us specific
          consent to use your personal information for a specific purpose.
        </p>
        <p>
          ➢ Legitimate Interests: We may process your data when it is reasonably
          necessary to achieve our legitimate business interests.
        </p>
        <p>
          ➢ Performance of a Contract: Where we have entered into a contract
          with you, we may process your personal information to fulfil the terms
          of our contract.
        </p>
        <p>
          ➢ Legal Obligations: We may disclose your information where we are
          legally required to do so in order to comply with applicable law,
          governmental requests, a judicial proceeding, court order, or legal
          process, such as in response to a court order or a subpoena (including
          in response to public authorities to meet national security or law
          enforcement requirements).
        </p>
        <p>
          ➢ Vital Interests: We may disclose your information where we believe
          it is necessary to investigate, prevent, or take action regarding
          potential violations of our policies, suspected fraud, situations
          involving potential threats to the safety of any person and illegal
          activities, or as evidence in litigation in which we are involved
        </p>
        <p>
          More specifically, we may need to process your data or share your
          personal information to contractors, service providers, and other
          third parties we use to support our business; to fulfil the purpose
          for which you provide it; if we believe disclosure is necessary or
          appropriate to protect the rights, property, or safety of the Company,
          our customers, or others.
        </p>

        <p>
          ➢ Business Transfers: We may share or transfer your information in
          connection with, or during negotiations of, any merger, sale of
          company assets, financing, or acquisition of all or a portion of our
          business to another company.
        </p>
        <p>
          ➢ Affiliates: We may share your information with our affiliates, in
          which case we will require those affiliates to honour this privacy
          notice. Affiliates include our parent company and any subsidiaries,
          joint venture partners or other companies that we control or that are
          under common control with us.
        </p>
        <p>
          ➢ Business Partners: We may share your information with our business
          partners to offer you certain products, services or promotions.
        </p>

        <h1>HOW DO WE HANDLE YOUR SOCIAL LOGINS?</h1>

        <p>
          In Short: If you choose to register or log in to our services using a
          social media account, we may have access to certain information about
          you.
        </p>
        <p>
          Our Services offers you the ability to register and login using your
          third-party social media account details (like your Facebook or
          Twitter logins). Where you choose to do this, we will receive certain
          profile information about you from your social media provider. The
          profile information we receive may vary depending on the social media
          provider concerned, but will often include your name, email address,
          friends list, profile picture as well as other information you choose
          to make public on such social media platforms.
        </p>

        <p>
          We will use the information we receive only for the purposes that are
          described in this privacy notice or that are otherwise made clear to
          you on the relevant Services. Please note that we do
        </p>
        <p>
          not control, and are not responsible for, other uses of your personal
          information by your thirdparty social media provider. We recommend
          that you review their privacy notice to understand how they collect,
          use and share your personal information, and how you can set your
          privacy preferences on their sites and apps.
        </p>

        <h1>DATA SAFETY AND ANTI PHISHING ALERT </h1>

        <p>
          We have implemented appropriate technical and organizational security
          measures designed to protect the security of any personal information
          we process. However, despite our safeguards and efforts to secure your
          information, no electronic transmission over the Internet or
          information storage technology can be guaranteed to be 100% secure, so
          we cannot promise or guarantee that hackers, cybercriminals, or other
          unauthorized third parties will not be able to defeat our security,
          and improperly collect, access, steal, or modify your information.
          Although we will do our best to protect your personal information,
          transmission of personal information to and from our Services is at
          your own risk. You should only access the Services within a secure
          environment.
        </p>

        <p>
          Hackers or other malicious groups or organizations may attempt to
          interfere with the Platforms in a variety of ways, including, but not
          limited to, malware attacks, denial of service attacks,
          consensus-based attacks, phishing attacks, smurfing and spoofing
          (‘Hacking Attack(s)’). Although we make reasonable efforts to secure
          our platform and Our Users against such incidents, we cannot guarantee
          that our platform and Our Users will be protected. We will not accept
          any claims from any damages or losses arising from Hacking Attacks and
          will not indemnify anyone for losses resulting from a Hacking Attack
          linked to Use of our Platform. Users are requested to maintain extreme
          caution and take steps to protect themselves from losses by
          maintaining an absolute minimum amount of funds on any online wallets.
        </p>

        <h2>Account Information</h2>
        <p>
          If you would at any time like to review or change the information in
          your account or terminate your account, you can:
        </p>
        <p>● Log in to your account settings and update your user account. </p>
        <p>● Contact us using the contact information provided.</p>

        <p>
          Upon your request to terminate your account, we will deactivate or
          delete your account and information from our active databases.
          However, we may retain some information in our files to prevent fraud,
          troubleshoot problems, assist with any investigations, enforce our
          Terms of Use and/or comply with applicable legal requirements.
        </p>

        <p>
          Cookies and similar technologies: Most Web browsers are set to accept
          cookies by default. If you prefer, you can usually choose to set your
          browser to remove cookies and to reject cookies. If you choose to
          remove cookies or reject cookies, this could affect certain features
          or services of our Services. To opt-out of interest-based advertising
          by advertisers on our Services visit http://www.aboutads.info/choices/
          .
        </p>
        <p>
          Opting out of email marketing: You can unsubscribe from our marketing
          email list at any time by clicking on the unsubscribe link in the
          emails that we send or by contacting us using the details provided
          below. You will then be removed from the marketing email list however,
          we may still communicate with you, for example to send you
          service-related emails that are necessary for the administration and
          use of your account, to respond to service requests, or for other
          non-marketing purposes. To otherwise opt-out, you may:
        </p>
        <p>● Access your account and update your preferences</p>
        <p>● Contact us using the contact information provided</p>
        <h3>UPDATING OF PRIVACY POLICY </h3>
        <p>
          We may update our Privacy Policy from time to time. The updated
          version will be posted on this page and will be effective as soon as
          it is accessible. We may notify you by sending a direct notification
          prior to the change becoming effective.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <h4>
          HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?
        </h4>
        <p>
          Based on the applicable laws of your country, you may have the right
          to request access to the personal information we collect from you,
          change that information, or delete it in some circumstances
        </p>
        <h5>GOVERNING LAWS </h5>
        <p>
          The agreement and your use of the service will be governed by the laws
          of UTTAR PARDESH, India.
        </p>
        <p>
          Your use of the service may also be subject to some other local,
          state, national or international laws.
        </p>
        <h6>CONTACT</h6>
        <p>
          If you have questions or comments about this notice, you may email us
          at thinkwht@gmail.com, call on +91-6387889987 or by post to:
          Ramprastha City, The edge Sector 37D Gurgaon, Haryana 122004
        </p>
      </div>
    </div>
  );
};

export default Privacy;
